### ISSUE TITLE
Regressions

### ISSUE THREAD

**Issue by bgribaudo** [microsoft/vscode-powerquery-sdk#137] opened 2022-09-30 14:55 UTC
The following issues were reported as fixed in 0.1.5 yet can still be reproduced:
#100
#111

I don't have a way to reopen closed issues, so noting this in a separate issue to make sure these don't slip through the cracks.

**Comment by mattmasson** [comment] 2022-09-30 16:20
I see what the problem is. Our serializer relies on the table type. If table metadata is telling us `type any`, we end up going down the generic JSON serializer route. 

```powerquery
    #table(
        type table [ Column1 = Duration.Type, Column2 = Date.Type ],
        {
            {#duration(1,2,3,4), #date(2022, 1, 1)}
        }
    );
```
```json
{
      "Output": [
          {
              "Column1": "1.02:03:04",
              "Column2": "2022-01-01"
          }
      ]
}
```

This entire layer will be replaced in the near future, so I'm not sure we'll want to redo all of the date serialization logic right now. Duration / Timespan might be easier to tackle.

**Comment by mattmasson** [comment] 2022-10-04 17:05
The persistence of `duration` and `time` values will be fixed in the next SDK Tools update.

I can't do anything about `date`/`datetime` if the schema type isn't set on the result.

**Closed by mattmasson** 2022-10-04 17:05 UTC
Labels: sdk tools
