### ISSUE TITLE
Regression or Purposeful Change? - PQTest.exe set-credential -ak Anonymous

### ISSUE THREAD

**Issue by bgribaudo** [microsoft/vscode-powerquery-sdk#189] opened 2022-11-04 18:58 UTC
The 0.2.0 release removes the `-ak Anonymous` argument from the command line that is rendered out when setting an anonymous credential.

With 0.2.0, performing an anonymous credentials set results in the following being output:
````
[2:49:44 PM]	[Info]	[Task found] c:\Users\ben\.vscode\extensions\powerquery.vscode-powerquery-sdk-0.2.0-win32-x64\.nuget\Microsoft.PowerQuery.SdkTools.2.110.3\tools\PQTest.exe set-credential
				--extension "c:\Users\ben\Desktop\TestConnector\BenTest\bin\AnyCPU\Debug\BenTest.mez"
				--queryFile "c:\Users\ben\Desktop\TestConnector\BenTest\BenTest.query.pq"
				--prettyPrint
````

However, the picture associated with PR #160 shows the set credentials output as containing `-ak Anonymous`, making me suspect that that argument should still be rendered out. Should it?

**Comment by bgribaudo** [comment] 2022-11-04 18:59
Related: #156

**Comment by mattmasson** [comment] 2022-11-04 19:39
Are you hitting an error, or just a mismatch of what is included in the trace?

**Comment by bgribaudo** [comment] 2022-11-04 19:47
No error. Just the trace output changed from 0.1.7 and is different from what the PR's screenshot showed.

**Comment by albertli-msft** [comment] 2022-11-22 08:10
Hi Ben @bgribaudo : 

This is not a regression, Matt enhanced it as we no longer need auth kind when a template string got provided.
Thus, previously:
    Shown in screenshot of the last pr, there is a -ak argument.
Currently,
    After https://github.com/microsoft/vscode-powerquery-sdk/pull/175
    There won't be any -ak arguments since we recognized it as a template.

Thank Ben for find this 😀, and i gonna close this ticket.

**Closed by albertli-msft** 2022-11-22 08:10 UTC
Labels: bug

**Comment by bgribaudo** [comment] 2022-11-22 13:00
Hi @albertli-msft,

That make sense: since a template is being used to define the anonymous credential, no `-ak` is required.

Thanks for all the work you are putting into this SDK!

Ben
