### ISSUE TITLE
Number Output Serialization - Truncated Values

### ISSUE THREAD

**Issue by bgribaudo** [microsoft/vscode-powerquery-sdk#101] opened 2022-09-22 21:33 UTC
In the output generated, some numbers are displayed using a truncated scientific notation syntax, even though Power Query internally stores the number with more precision. 

Example: `56789012345678901234567890` is rendered out as `5.6789012345678904e+25`. In contrast, in Query Editor, if an expression is defined as `56789012345678901234567890`, the output rendered to screen is the full `56789012345678901234567890`.

Request: Could the SDK's output be revised to display numbers with the same precision as Power Query sees them internally?

**Comment by ptyx507x** [comment] 2022-09-22 22:30
We have some plans to address and improve the current results panel :) 

Hopefully we'll be able to share more information about this in the near future, but we will absolutely take this feedback into consideration.

**Comment by mattmasson** [comment] 2022-09-24 00:36
Confirmed that we don't have an easy way to do this with the JSON serialization we're doing.

**Comment by mattmasson** [comment] 2022-09-24 17:01
The next tools update will have a number of improvements to the way we serialize values. The current value serialization format is temporary - we'll eventually be reusing the same formatter used in Power Query. I'm going to mark this issue as won't fix for now, because I couldn't figure out an easy short-term fix, and we should get this fix "for free" in the future.

**Closed by mattmasson** 2022-09-24 17:01 UTC
Labels: enhancement, wontfix

**Comment by bgribaudo** [comment] 2022-09-26 13:52
Nice! Thanks, @mattmasson. Appreciate all that you and the team are doing with this tool.
